### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by ionwebs** [jkenlooper/piecemaker#25]
> minimum_piece_size 27.29014844804318
max pieces that will fit 3021
pieces requested 100
pieces adjusted 100
pieces actual 100
piece size 150.0 x 150.0
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Scripts\piecemaker.exe\__main__.py", line 7, in <module>
  File "C:\Python311\Lib\site-packages\piecemaker\script.py", line 191, in piecemaker
    pieces = Pieces(
             ^^^^^^^
  File "C:\Python311\Lib\site-packages\piecemaker\base.py", line 91, in __init__
    scaled_png = rasterize_svgfile(scaled_svg, width, height)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\piecemaker\tools.py", line 44, in rasterize_svgfile
    subprocess.run(
  File "C:\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python311\Lib\subprocess.py", line 1493, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

Can you please suggest issue?, I am new in python.

**Comment by jkenlooper** [comment]
This project doesn't support directly running on a Windows machine. I suggest following the directions to run it with Docker. 

Leaving this issue open for now as the documentation isn't very exact on what platforms it will run on.
